# Generated by Django 5.0.1 on 2024-01-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=20)),
                ('state_of_origin', models.CharField(max_length=255)),
                ('dob', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=50)),
            ],
        ),
    ]
